const propertyData = [
    {
        id: 1,
        title: "Modern 2 Bedroom Apartment",
        location: "Lekki Phase 1, Lagos",
        price: 2500000,
        priceLabel: "₦2,500,000",
        period: "year",
        type: "Apartment",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,200 sq ft",
        status: "verified",
        verified: true,
        agent: "Prime Realty",
        views: 248,
        inquiries: 12,
        image:
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
    },

    {
        id: 2,
        title: "Luxury 3 Bedroom Apartment",
        location: "Ikeja GRA, Lagos",
        price: 3200000,
        priceLabel: "₦3,200,000",
        period: "year",
        type: "Apartment",
        bedrooms: 3,
        bathrooms: 3,
        area: "1,650 sq ft",
        status: "verified",
        verified: true,
        agent: "Urban Nest Properties",
        views: 391,
        inquiries: 18,
        image:
            "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80",
    },

    {
        id: 3,
        title: "Contemporary 4 Bedroom Duplex",
        location: "Wuse 2, Abuja",
        price: 4800000,
        priceLabel: "₦4,800,000",
        period: "year",
        type: "Duplex",
        bedrooms: 4,
        bathrooms: 4,
        area: "2,400 sq ft",
        status: "verified",
        verified: true,
        agent: "Capital Homes",
        views: 512,
        inquiries: 24,
        image:
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80",
    },

    {
        id: 4,
        title: "Elegant 3 Bedroom Terrace",
        location: "Yaba, Lagos",
        price: 2800000,
        priceLabel: "₦2,800,000",
        period: "year",
        type: "Terrace",
        bedrooms: 3,
        bathrooms: 3,
        area: "1,800 sq ft",
        status: "pending",
        verified: false,
        agent: "HomeFind NG",
        views: 174,
        inquiries: 7,
        image:
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80",
    },

    {
        id: 5,
        title: "Spacious 2 Bedroom Flat",
        location: "Gwarinpa, Abuja",
        price: 1900000,
        priceLabel: "₦1,900,000",
        period: "year",
        type: "Apartment",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,100 sq ft",
        status: "verified",
        verified: true,
        agent: "Abuja Living",
        views: 205,
        inquiries: 9,
        image:
            "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=80",
    },

    {
        id: 6,
        title: "Premium 4 Bedroom Family Home",
        location: "Chevron, Lekki",
        price: 6500000,
        priceLabel: "₦6,500,000",
        period: "year",
        type: "Duplex",
        bedrooms: 4,
        bathrooms: 5,
        area: "3,100 sq ft",
        status: "verified",
        verified: true,
        agent: "Lagos Prime Estates",
        views: 638,
        inquiries: 31,
        image:
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80",
    },
];

export default propertyData;